version: "3.8"

services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mern_db:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: prod
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/stokify
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: prod
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mern_db:
